### ISSUE TITLE
SELinux support for `oci create-image`

### ISSUE THREAD

**Issue by travier** [containers/composefs-rs#29]
The `oci create-image` command should label all the files using the default labels set in the policy from the container.

If a user wants to change a label for a file, they can modify the SELinux policy file mapping using semanage in a container layer and that will be taken into account by this.

To do that, we need to lookup all the files labels when we create the composefs blob.

Looking up a file label is done like that in C (from Allison's code):

```
#include <stdlib.h>
#include <unistd.h>
#include <selinux/label.h>
#include <selinux/selinux.h>
#include <sys/stat.h>
#include <err.h>
#include <stdio.h>
 
int
main (int argc, char **argv)
{
    struct selinux_opt opts[] = {
    };
 
 
  struct selabel_handle *hnd = selabel_open (SELABEL_CTX_FILE, opts, 0);
 
  for (int i = 1; i < argc; i++)
    {
      struct stat buf;
 
      if (lstat (argv[i], &buf) != 0)
        err(EXIT_FAILURE, "stat %s: ", argv[i]);
 
      char *ctx = NULL;
      if (selabel_lookup (hnd, &ctx, argv[i], buf.st_mode & S_IFMT) != 0)
        err(EXIT_FAILURE, "selabel_lookup('%s', %d): ", argv[i], buf.st_mode & S_IFMT);
 
      printf ("%s → %s\n", argv[i], ctx);
      freecon (ctx);
    }
 
  selabel_close (hnd);
}
```

As we need to use the SELinux policy from the container, we need to:
- figure out which policy is going to be used (or maybe we just extract all the policy available?)
- extract the SELinux file contexts mapping files from the container to a temporary path:
  - `/etc/selinux/{SELINUXTYPE}/contexts/files/file_contexts`
  - ...
  - See https://man7.org/linux/man-pages/man5/selabel_file.5.html
-  point libselinux to the extracted `files_contexts` by setting the folllowing `selinux_opt`:
  - `SELABEL_OPT_PATH` -> `/path/to/etc/selinux/{SELINUXTYPE}/contexts/files/file_contexts`

**Comment by travier** [comment]
Example custom SELinux context in https://gitlab.com/fedora/bootc/tests/container-fixtures/-/merge_requests/13.

**Comment by allisonkarlitskaya** [comment]
This is going to go something like this (discussed with @travier in a super-productive call):
 - during `cfsctl oci create-image` after the layer merge but before calling mkcomposefs:
   - create a tempdir
   - use `composefs::fs::write_to_path()` to extract `/etc/selinux/` of the merged container image to the tempdir
   - `selabel_open()` the policy from the tempdir
   - walk the filesystem tree doing a selinux query for each inode, adding xattrs as we go
 - call `mkcomposefs`

Risks: we're using libselabel from the host system which is yet another moving part in our must-be-super-deterministic pipeline.  That means that if something changes in a way that affects some image (some regexp engine bugfix or so) we're going to invalidate our composefs fs-verity digest.

Future: we should ask libselabel about an API that lets us feed the policy directly instead of needing to unpack to a tempdir.  Maybe such an API already exists, or maybe they'd be willing to add it for us.

**Comment by allisonkarlitskaya** [comment]
Further future: we probably want to move as much of this as possible to the server/build side.  In the case that we're created a sealed UKI image then it definitely makes sense to do the entire computation there, producing new tar layers with the xattrs already baked in.  But we need to be able to work with these two situations:
 - the user derives a base image and adds some file (which needs to get labelled)
 - the user derives a base image and modifies the policy (which means the entire system needs to be potentially relabelled)

Those two cases mean that we need the labelling support already on the client side anyway, so we may as well go ahead and develop it.  We can do the optimization of moving it "build side" for performance reasons if/after we discover performance problems.

**Comment by cgwalters** [comment]
> Risks: we're using libselabel from the host system which is yet another moving part in our must-be-super-deterministic pipeline. 

Our examples should use the `FROM oci-archive` trick by default which links everything into a container build pipeline and ensures host independence. (We can still support being run outside of a containerfile too of course, but I think the "Containerfile is entrypoint" is the right default)
