### ISSUE TITLE
Import and compute composefs' fs-verity in a multi-staged build

### ISSUE THREAD

**Issue by travier** [containers/composefs-rs#34]
In order to be able to run the entire build process from a multi-staged build via a single Containerfile build, we need cfsctl to read the OCI content using a --mount/--from option like in https://gitlab.com/fedora/bootc/base-images/-/blob/main/Containerfile.

cfsctl would read the entire container archive, generate the composefs dumpfile, pass it to mkcomposefs and finally get the fs-verity of the resulting EROFS.

Then this layer could build the UKI using this fs-verity-hash.

As we need this hash as a label (i.e. outside of the container), we would then store that as a file or output that on stdout at the end and another step in the build process would add the hash as a label (as it's not possible to add labels with values generated from stages right AFAIK).

**Comment by allisonkarlitskaya** [comment]
https://github.com/containers/buildah/issues/5837 would be a huge help here, but we could also do it by scanning the filesystem in a normal bind mount, and hopefully we can get the same result.

**Comment by allisonkarlitskaya** [comment]
I have a working branch for this.  The two composefses are equal with one major issue: when we create a composefs from the image via layer tarballs we use the epoch as the mtime for `/` because `/` never explicitly appears in a layer.  The mtime of the root of a container image as inspected inside of podman appears to be equal to the time at which podman unpacked that layer (ie: at `podman build` or `podman pull` time: nothing deterministic).

Using the epoch feels slightly terrible but it's better than something essentially chosen at random.

**Comment by allisonkarlitskaya** [comment]
Or here are three variations on the same theme:
 - the mtime of the root directory is set to be the same is the most recent mtime of the files present in the root directory; or
 - the mtime of the root directory is set to be the same as the most recent mtime in the entire filesystem; or
 - each directory has its mtime set to the most recent mtime of any entry.  this would apply transitively (so generalizes the first and ends up also satisfying the second in the process)

The last option has a certain appeal but it's also the most "destructive" of all the options and it has an additional problem: I'm not sure how well it would play with things like the various icon/mime/etc cache files which are supposed to be newer than the directories that contain them.  We'd have to read those specs carefully, and hope that there's not some other spec that we didn't consider which we accidentally break.

**Comment by cgwalters** [comment]
Hmm shouldn't it just be the mtime of the tar entry that contained the root?

**Comment by allisonkarlitskaya** [comment]
> Hmm shouldn't it just be the mtime of the tar entry that contained the root?

That's exactly the problem.  There isn't one.

**Comment by allisonkarlitskaya** [comment]
There's actually an additional issue here: we might reasonably assume that the owner of the root directory is `root:root` but it's not clear what the permissions should be.  I've hardcoded them to `0755` based on gut instinct, and this is what they are on my (ostree) booted system and `/sysroot`, but podman actually picks `0555` for this purpose, so that's one more difference we have to figure out how to paper over.

We definitely need solid specs around these things.  They impact the determinism of the process of producing the image.

**Comment by travier** [comment]
> I've hardcoded them to `0755` based on gut instinct, and this is what they are on my (ostree) booted system and `/sysroot`, but podman actually picks `0555` for this purpose, so that's one more difference we have to figure out how to paper over.

`555` is nice as it reflects that even root can not change those files. If podman uses it then I guess it should be fine? `755` should be just fine as well.

**Comment by cgwalters** [comment]
> That's exactly the problem. There isn't one.

There is in the fedora-bootc image:

```
tar tvf fedora-oci/blobs/sha256/2dbcdb8a850237b5ccdfeadb58518e23fc4d0e969d475835829935d5010d080d | head
drwxr-xr-x 0/0               0 1969-12-31 19:00 ./
drwxr-xr-x 0/0               0 1969-12-31 19:00 sysroot
drwxr-xr-x 0/0               0 1969-12-31 19:00 sysroot/ostree
```

But yeah, there isn't one in `quay.io/fedora/fedora` or `docker.io/library/debian`. I think we should encourage this though, *especially* for bootable containers because another thing that arises here if we just make up an entry for `/` is what the selinux label is (for sealed images we shouldn't be computing it client side).

So let's honor the tar stream if it exists, otherwise fall back.

**Comment by allisonkarlitskaya** [comment]
> So let's honor the tar stream if it exists, otherwise fall back.

Agree complete.  I'm about to push a branch, and this is exactly what I wrote in the documentation that I added.

**Comment by cgwalters** [comment]
(Whether `/` is present or not is also something that would be important for "canonical tar")

**Comment by allisonkarlitskaya** [comment]
> I went with "newest file overall". It's also easy to find out. Note that every time we're importing a filesystem we're scanning the entire thing. Keeping this one extra tiny bit of state around ends up not being difficult at all.

This turned out to be naive.  Simply taking the newest mtime from each tar entry is definitely wrong because it doesn't take whiteouts into account (both the whiteout itself, plus the file that it deletes).
