### ISSUE TITLE
unified image build, Error: xattrs changed during read

### ISSUE THREAD

**Issue by shawn111** [containers/composefs-rs#41]
composefs-rs/examples/unified $ ./build

```
[2/3] STEP 1/3: FROM 4d08a5ad0f7b068e4fb32adfb25f3c542f05c4939372c3c521e7dfeab5b06a53 AS kernel
[2/3] STEP 2/3: RUN --mount=type=bind,from=base,target=/mnt/base <<EOF (set -eux...)
+ mkdir -p /tmp/sysroot/composefs/images
+ mkdir -p /tmp/sysroot/composefs/objects
++ cfsctl --repo /tmp/sysroot create-image /mnt/base
Error: xattrs changed during read
```

I can build bls or uki image, but unified failed in kernel stage.

**Comment by allisonkarlitskaya** [comment]
So the issue is this:

```
listxattr("/proc/self/fd/4", 0x1, 0)    = 38
listxattr("/proc/self/fd/4", "security.selinux\0", 38) = 17
```

we get told that we should expect 38 bytes worth of xattr names but then there's only 17 there.  I bet you the 38 includes some of the overlayfs trusted attributes that aren't actually being returned in the end.  That sounds like a kernel bug (in overlayfs)...

We should probably try to deal with that gracefully anyway, though.

**Comment by allisonkarlitskaya** [comment]
I just checked the code for overlayfs and this is indeed exactly what's happening:

https://github.com/torvalds/linux/blob/cdd30ebb1b9f36159d66f088b61aee264e649d7a/fs/overlayfs/xattrs.c#L125

There is a shortcut if the requested size is `0` and the filtering out of the private attributes occurs after that shortcut.  I'm not sure if this is a violation of POSIX or not, but let's change it on our side to be more tolerant.

**Comment by allisonkarlitskaya** [comment]
@shawn111 can you please test #43 ?

**Comment by shawn111** [comment]
The error is different but still failed.

```
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_DROPPABLE|MAP_ANONYMOUS, -1, 0) = 0x7f5af86f1000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5af86f0000
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
getrandom("\x01\x1e\x96\xd1\x56\xfd\xc3\x0f\x43\xe5\x4f\xd2\xcf\x05\xf1\xc7\x3d\xaa\xdf\x93\x73\xcd\x44\x09\xae\xfe\xe1\xea\x25\x81\x82\x3d", 32, 0) = 32
openat(AT_FDCWD, "/mnt/base", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 4
fstat(4, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
listxattr("/proc/self/fd/4", 0x1, 0)    = 38
listxattr("/proc/self/fd/4", "security.selinux\0", 38) = 17
getxattr("/proc/self/fd/4", "security.selinux", "system_u:object_r:container_file"..., 65536) = 48
fcntl(4, F_GETFL)                       = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
openat(4, ".", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 5
getdents64(5, 0x55f0e07527a0 /* 24 entries */, 768) = 608
openat(4, ".profile", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=1004, ...}) = 0
close(6)                                = 0
close(5)                                = 0
close(4)                                = 0
flock(3, LOCK_UN)                       = 0
close(3)                                = 0
write(2, "Error: ", 7Error: )                  = 7
write(2, "Attempting to cross devices whil"..., 54Attempting to cross devices while importing filesystem) = 54
write(2, "\n", 1
)                       = 1
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7f5af8a00000, 12288)           = 0
exit_group(1)                           = ?
+++ exited with 1 +++
+ COMPOSEFS_FSVERITY=
Error: building at STEP "RUN --mount=type=bind,from=base,target=/mnt/base <<EOF": while running runtime: exit status 1
```

**Comment by allisonkarlitskaya** [comment]
Based on the

```
listxattr("/proc/self/fd/4", 0x1, 0)    = 38
listxattr("/proc/self/fd/4", "security.selinux\0", 38) = 17
getxattr("/proc/self/fd/4", "security.selinux", "system_u:object_r:container_file"..., 65536) = 48
fcntl(4, F_GETFL)                       = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
```

I'm fairly confident that the fix in #43 was effective.

The latest error message happens when we see different `.st_dev` across `stat()` calls.  I wonder if that's another overlayfs/composefs peculiarity...

@cgwalters had an idea to do this with `RESOLVE_NO_XDEV` and `openat2()`.  I agree that this is a better approach but punted on it because the implementation was thorny.  Maybe it's time to look at that again.

**Comment by allisonkarlitskaya** [comment]
@shawn111 you could test this theory:

> The latest error message happens when we see different .st_dev across stat() calls. I wonder if that's another overlayfs/composefs peculiarity...

by using `strace -v` to avoid getting the `stat buf` truncated in the output...

**Comment by shawn111** [comment]
Thank you very much, I will try tomorrow.

**Comment by allisonkarlitskaya** [comment]
> @cgwalters had an idea to do this with RESOLVE_NO_XDEV and openat2(). I agree that this is a better approach but punted on it because the implementation was thorny. Maybe it's time to look at that again.

Actually, I just realized that this might be a bad idea.  I actually don't care at all about the cross-device question.  The thing I actually care about is the uniqueness of `st_ino`, since I build a hardlink-tracking hashtable based on it.  Ensuring unique `st_dev` was only a way to make sure that `st_ino` values are sensible.  If we're seeing a different `.st_dev` because of some weird overlayfs effects then `RESOLVE_NO_XDEV` isn't going to save us here.

I think what I actually need to do is to just key the hashtable on the `.st_dev`/`.st_ino` combination.

**Comment by cgwalters** [comment]
> I think what I actually need to do is to just key the hashtable on the .st_dev/.st_ino combination.

Makes sense to me yes (it's what ostree does, as do many other tools AFAIK)
